### ISSUE TITLE
Update to latest Gamelift SDK

### ISSUE THREAD

**Issue by oskarlu** [britzl/defold-gamelift#2]
We (StrangeQuest) have an open support issue with Gamelift that we can’t take any further now until we’ve updated our Gamelift SDK/wrapper. They claim/hope that updating will help resolve some SDK disconnects.

**Comment by oskarlu** [comment]
Andreas found out that Ted forked your repo and made a change to gamelift.cpp:GameLift_OnHealthCheck(), basically commented out the whole impl and always return true.

You can find it here, tho I'm not sure what to do with this information...
https://github.com/strangequest/defold-gamelift/blob/master/gamelift/src/gamelift.cpp

**Comment by britzl** [comment]
Created a branch: https://github.com/britzl/defold-gamelift/tree/update_to_gamelift_3.3.0

The branch contains the latest version of the Gamelift SDK (3.3.0) with libs built for OSX.
I'd appreciate if you could download the SDK and build for Linux and make a PR once you've verified that it works

Building on OSX and Linux is super simple. It should be enough to follow the basic build instructions from the readme:

```
mkdir out
cd out
cmake ..
make

```
And then copy the libs from out/prefix/lib/ to the gamelift extension

**Comment by britzl** [comment]
Upgraded to 3.3.0, merged and released:

https://github.com/britzl/defold-gamelift/releases/tag/1.1.0
