### ISSUE TITLE
Separate processReady from init

### ISSUE THREAD

**Issue by oskarlu** [britzl/defold-gamelift#5]
We want to be able to first call initSDK, then do some other stuff on Lua side before telling Gamelift we're ready to receive GameSessions. Right now both InitSDK() and ProcessReady() are called from within gamelift.cpp::InitGamelift so those steps would have to be separated, and processReady be exposed to Lua.

**Comment by britzl** [comment]
Could you do the other stuff first and then call gamelift.init()? Why the need to call init first and then process ready?

**Comment by oskarlu** [comment]
That’s what we’re doing now but if other stuff (gamesparks auth) takes longer than 5 mins (it happens) we don’t call gamelift.init before it reaches a gamelift timeout (of time spent between server boot and calling init) and we suspect this is causing trouble.

/Oskar

**Comment by britzl** [comment]
Please give this branch a try: https://github.com/britzl/defold-gamelift/tree/separate_init_and_process_ready

```
-- initialize gamelift sdk
gamelift.init(port, on_start_game_session_listener, on_process_terminate_listener, on_health_check_listener)

-- indicate that the server process is ready
gamelift.process_ready()
```
